kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "persistentvolumes", "persistentvolumeclaims", "services" ]
    verbs: [ "get", "list", "create", "delete" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "create", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "create", "delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "create", "delete" ]
  - apiGroups: [ "stable.dwk" ]
    resources: [ "dummysites" ]
    verbs: [ "get", "list", "watch", "create", "delete" ]
