apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: 2kai/k8s-school-ping-pong:3.02
          envFrom:
            - configMapRef:
                name: ping-pong-cm
            - secretRef:
                name: ping-pong-postgres-secret
