apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ping-pong-ingress-route
spec:
  routes:
    - match: PathPrefix(`/pingpong`)
      kind: Rule
      services:
        - name: ping-pong-svc
          port: 2345
      middlewares:
        - name: ping-pong-middleware
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ping-pong-middleware
spec:
  stripPrefix:
    prefixes:
      - /pingpong
