apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
  namespace: project
spec:
  metrics:
    - name: cpu-usage-rate
      initialDelay: 1m
      successCondition: result < 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1639-prometheus.prometheus.svc.cluster.local:9090
          query: scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project"}[10m]))*10)
