apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-project-daily-todo-cronjob
  namespace: project
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            linkerd.io/inject: enabled
        spec:
          containers:
            - name: daily-todo
              image: 2kai/k8s-school-todo-project-api:4.06
              envFrom:
                - configMapRef:
                    name: todo-project-cm
                - secretRef:
                    name: todo-project-postgres-secret
              command:
                - /bin/sh
                - -c
                - node src/daily-todo.js
          restartPolicy: OnFailure
