apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project-frontend
  template:
    metadata:
      labels:
        app: todo-project-frontend
    spec:
      containers:
        - name: todo-project
          image: gcr.io/devops-with-kubernetes-291121/k8s-school-todo-project-frontend
          resources:
            requests:
              cpu: "150m"
              memory: "750Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-api-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project-api
  template:
    metadata:
      labels:
        app: todo-project-api
    spec:
      volumes:
        - name: daily-image-volume
          persistentVolumeClaim:
            claimName: common-claim
      containers:
        - name: todo-project
          image: gcr.io/devops-with-kubernetes-291121/k8s-school-todo-project-api
          envFrom:
            - configMapRef:
                name: todo-project-cm
            - secretRef:
                name: todo-project-postgres-secret
          volumeMounts:
            - name: daily-image-volume
              mountPath: /opt/src/daily/
          resources:
            requests:
              cpu: "150m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "100Mi"
