apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-project-frontend-ing
  namespace: project
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-project-frontend-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-project-api-svc
                port:
                  number: 80
