apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-project-frontend-ing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-project-frontend-svc
                port:
                  number: 2345
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: todo-project-api-ingress-route
spec:
  routes:
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: todo-project-api-svc
          port: 2345
      middlewares:
        - name: todo-project-api-middleware
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: todo-project-api-middleware
spec:
  stripPrefix:
    prefixes:
      - /api
