apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - cronjob.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - postgres.yaml
  - postgres-secret.yaml
  - rollout.yaml
  - service.yaml
  - telegram-secret.yaml
images:
  - name: 2kai/k8s-school-todo-project-api
    newName: 2kai/k8s-school-todo-project-api
    newTag: latest
  - name: 2kai/k8s-school-todo-project-frontend
    newName: 2kai/k8s-school-todo-project-frontend
    newTag: latest
  - name: 2kai/k8s-school-todo-project-broadcaster
    newName: 2kai/k8s-school-todo-project-broadcaster
    newTag: latest
