apiVersion: v1
kind: Service
metadata:
  name: todo-project-frontend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: todo-project-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-project-api-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: todo-project-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
