apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/cronjob.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres.yaml
  - manifests/postgres-secret.yaml
  - manifests/service.yaml
