apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: hash-generator
          image: 2kai/k8s-school-hash-generator:latest
