name: Log output application
on:
  push:
#    branches:
#      - master
    paths:
      - log-output/**
jobs:
  build-and-push-107:
    name: Build and push application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push 1.07
        uses: docker/build-push-action@v2
        with:
          context: log-output
          target: e107
          push: true
          tags: 2kai/k8s-school-log-output-1-07
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Build and push writer
        uses: docker/build-push-action@v2
        with:
          context: log-output
          target: writer
          push: true
          tags: 2kai/k8s-school-log-output-writer
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Build and push reader
        uses: docker/build-push-action@v2
        with:
          context: log-output
          target: reader
          push: true
          tags: 2kai/k8s-school-log-output-reader
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
