name: TODO project application
on:
  push:
    branches-ignore:
      - master
    paths:
      - todo-project/**
jobs:
  build-and-push:
    name: Build and push application
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo "::set-output name=branch::$(echo -n "${GITHUB_REF#refs/*/}")"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: todo-project/frontend
          push: true
          tags: |
            2kai/k8s-school-todo-project-frontend:${{ steps.vars.outputs.branch }}
            2kai/k8s-school-todo-project-frontend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          context: todo-project/api
          push: true
          tags: |
            2kai/k8s-school-todo-project-api:${{ steps.vars.outputs.branch }}
            2kai/k8s-school-todo-project-api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
